name: YouPeopleGame
version: 0.1-alpha
main: me.jho5245.youpeoplegame.YouPeopleGame
api-version: 1.21
author: jho5245
description: YouPeopleGame OMG WHAT?!
depend: [Cucumbery]

commands:
  testcommand2:
    description: 테스트 명령어
    aliases: [yi]
  youpeoplegame:
    description: YouPeopleGame GUI 명령어
    aliases: [game, 게임, rpdla, ㅎ믇]
  giveup:
    description: 점프맵 포기 명령어
  material-storage:
    description: 재료 가방 명령어
    usage: /<command> <get|store|show> <아이템 이름> [개수]
    aliases: [gfs, mst, mstorage, materialstorage, 재료-가방, 재료가방]
  item-storage:
    description: 아이템 가방 명령어
    usage: /<command> [아이템 가방 번호]
    aliases: [ist, itemstorage, istorage, 아이템-가방, 아이템가방]
  buff:
    description: 현재 버프 확인 명령어
    usage: /<command>
    aliases: [버프]
