name: YouPeopleGame
version: 0.1-alpha
main: me.jho5245.youpeoplegame.YouPeopleGame
api-version: 1.21
author: jho5245
description: YouPeopleGame OMG WHAT?!
depend: [Cucumbery]

commands:
  testcommand2:
    description: 테스트 명령어
  youpeoplegame:
    description: YouPeopleGame GUI 명령어
    aliases: [game, 게임, rpdla, ㅎ믇]
  giveup:
    description: 점프맵 포기 명령어
  gfs:
    description: 보관함 명령어
    usage: /<command> <get|store> <아이템 이름> [개수]
    aliases: [보관함, 가방, getfromsack, rkqkd, ckdrh, qhrhksgka]
